name: Release Publish

on:
  # 手动触发
  workflow_dispatch:
  # 发布到npm
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          # node版本
          node-version: 20
          registry-url: https://registry.npmjs.org/
          # 缓存依赖
          cache: npm

      - name: Install
        run: npm run install:all

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx changeset tag
          commit: "chore: :rewind: release version"
          title: "chore: release version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Visual Studio Marketplace
        if: steps.changesets.outputs.published == 'true'
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
