name: Release Publish

on:
  # 手动触发
  workflow_dispatch:
  # 发布到npm
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          # node版本
          node-version: 20
          registry-url: https://registry.npmjs.org/
          # 缓存依赖
          cache: npm

      - name: Install
        run: npm install --frozen-lockfile

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          # 构建发布
          publish: npm run release
          # 只发布release
          # publish: npx changeset tag
          commit: "chore: :rewind: release version"
          title: "chore: release version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      # 自定义发布流程
      # - name: Custom Publish
      #   if: steps.changesets.outputs.published == 'true'
