name: Test Action

on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test Action
        uses: ./
        id: test-action
        with:
          message: 'Hello, World!'

      - name: Print Output
        run: 'echo Output: ${{ steps.test-action.outputs.result }}'
