### test admin role
GET http://localhost:8080/test/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNDEwMDQzNCwianRpIjoiNzQ0MjA0MmYtZmRjNC00ZDM5LTljYTctZTU0OWNmOTI5MDM2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNzE0MTAwNDM0LCJjc3JmIjoiZmYxMjU1ZmYtMmNiOS00NjM3LWE3MjItNDU4NzI5MmZkOTgzIiwiZXhwIjoxNzE0MTAxMzM0LCJyb2xlcyI6WyJ1c2VyIl0sInNjb3BlcyI6W119.myq7sOlClKqxbSCn6DWftHxRDzKrsLR5CDVOyzNTP4c


### test user role
GET http://localhost:8080/test/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNDEwMDQzNCwianRpIjoiNzQ0MjA0MmYtZmRjNC00ZDM5LTljYTctZTU0OWNmOTI5MDM2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNzE0MTAwNDM0LCJjc3JmIjoiZmYxMjU1ZmYtMmNiOS00NjM3LWE3MjItNDU4NzI5MmZkOTgzIiwiZXhwIjoxNzE0MTAxMzM0LCJyb2xlcyI6WyJ1c2VyIl0sInNjb3BlcyI6W119.myq7sOlClKqxbSCn6DWftHxRDzKrsLR5CDVOyzNTP4c