version: 1

disable_existing_loggers: false

formatters:
  simple_formatter:
    format: "%(asctime)s.%(msecs)04d %(levelname)-8s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console_handler:
    class: logging.StreamHandler
    formatter: simple_formatter
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: simple_formatter
    filename: log/app.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

loggers:
  "sqlalchemy.engine":
    handlers:
      - console_handler
      - file_handler

root:
  handlers:
    - console_handler
    - file_handler
